version: '3'

services:
  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_DB: sivdev
      POSTGRES_USER: sivpack
      POSTGRES_PASSWORD: sivpack_dev
    ports:
      - "9432:5432"
  web:
    build:
      context: .
    image: app_web
    command: ["gunicorn", "app:app", "-b", "0.0.0.0:5000", "--reload", "--timeout",  "100000"]
    depends_on:
      - db
    volumes:
      - .:/home/web/
      - ./.pdbrc.py:/home/sivpack/.pdbrc.py
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
  migrate:
    image: boxfuse/flyway:4.2-alpine
    depends_on:
      - db
    command: -url=jdbc:postgresql://db/sivdev -user=sivpack -password=sivpack_dev migrate
    volumes:
      - ./sql:/flyway/sql
